service: tweeted-about-backend
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-esbuild

provider:
  name: aws
  stage: dev
  region: eu-west-1
  profile: kendi-hesabim
  tracing:
    lambda: true
  
  runtime: nodejs18.x
  memorySize: 512
  timeout: 10
  logRetentionInDays: 60

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 's3:*'
          Resource: '*'

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
        - aws-sdk
    platform: 'node'
    concurrency: 10
    plugins: ./esbuild-plugins.js

resources:
  Resources:
    tweetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: cihan-tweeted-about-backend-bucket

functions:
  authenticate:
    handler: src/lambda/auth.handler
    environment:
      AUTH0_AUDIENCE: tweeted-about-backend
      AUTH0_TOKEN_ISSUER: https://dev-ukwn2fwyghycs35o.us.auth0.com/
      AUTH0_JWKS_URI: https://dev-ukwn2fwyghycs35o.us.auth0.com/.well-known/jwks.json

  api:
    handler: src/lambda/api.handler
    timeout: 30
    events:
      - http:
          path: topics
          method: get
          cors: true
          authorizer: authenticate

    environment:
      AUTH0_ADMIN_AUDIENCE: https://dev-ukwn2fwyghycs35o.us.auth0.com/api/v2/
      AUTH0_ADMIN_CLIENT_SECRET: ${env:AUTH0_ADMIN_CLIENT_SECRET}
      AUTH0_ADMIN_CLIENT_ID: ${env:AUTH0_ADMIN_CLIENT_ID}
      AUTH0_TOKEN_URL: https://dev-ukwn2fwyghycs35o.us.auth0.com//oauth/token
      AUTH0_ADMIN_GET_USER_URL: https://dev-ukwn2fwyghycs35o.us.auth0.com/api/v2/users/
      TWITTER_CONSUMER_KEY: ${env:TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${env:TWITTER_CONSUMER_SECRET}
